# Generated by Django 4.2.2 on 2023-06-19 23:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('image', models.ImageField(max_length=1, upload_to='')),
                ('description', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('auteur', models.CharField(max_length=150)),
                ('cretate', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('pulish', models.DateTimeField(default=datetime.datetime(2023, 6, 19, 23, 25, 32, 235124, tzinfo=datetime.timezone.utc))),
                ('autors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
