# Generated by Django 4.2.2 on 2023-06-20 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_article_auteur_alter_article_pulish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pulish',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 13, 46, 5, 838301, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='titel',
            field=models.CharField(max_length=25),
        ),
    ]
