# Generated by Django 4.2.2 on 2023-06-20 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_pulish_alter_article_titel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='cretate',
            new_name='create',
        ),
        migrations.RemoveField(
            model_name='article',
            name='pulish',
        ),
        migrations.AddField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 14, 36, 1, 959995, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
