# Generated by Django 4.2.2 on 2023-06-20 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_cretate_article_create_remove_article_pulish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 14, 36, 26, 269809, tzinfo=datetime.timezone.utc)),
        ),
    ]
