# Generated by Django 4.2.2 on 2023-06-20 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 14, 44, 29, 806792, tzinfo=datetime.timezone.utc)),
        ),
    ]
