# Generated by Django 4.2.3 on 2023-07-13 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 21, 6, 59, 722596, tzinfo=datetime.timezone.utc)),
        ),
    ]
