# Generated by Django 4.2.3 on 2023-07-17 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_article_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 15, 54, 46, 260591, tzinfo=datetime.timezone.utc)),
        ),
    ]
