# Generated by Django 4.2.4 on 2023-08-08 19:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_article_description_alter_article_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='details',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
